### ISSUE TITLE
Can't dump with txd

### ISSUE THREAD

**Issue by ChristopherDrum** [the-infocom-files/bureaucracy#12]
Running `txd -d -n` on the z4 file generated with ZILF/ZAPF results in the error
```
Grammar table illegal size!
Fatal: game file read error
```
Dumping r116 (Masterpieces) works fine.

(I'm investigating a potential endgame sudden crash scenario which may have a relationship to this problem, but also may be an interpreter bug).

**Comment by heasm66** [comment]
Have you tried txd without decoding the grammar (with the ```-g``` switch)?

**Comment by ChristopherDrum** [comment]
Not yet, no. I just wonder if this points to a deeper issue with the source.

**Comment by ChristopherDrum** [comment]
`-g` did at least get me what I had hoped for, so I'll close this out.
