### ISSUE TITLE
Doesn't build under Linux

### ISSUE THREAD

**Issue by eriktorbjorn** [the-infocom-files/bureaucracy#3]
When trying to build the game under Linux, you get this somewhat unhelpful error:

```
[error MDL0604] bureaucracy.zil:33: INSERT-FILE: file not found: mumble
```

Actually, mumble.zil is there. The problem is that mumble.zil does this:

```
<LD-FILE "SS:<BUREAUCRACY>TEXT.FILE">
```

If I change that to

```
<LD-FILE "SS:<BUREAUCRACY>text.file">
```

it builds just fine. (Well, there are plenty of warnings with the development version of Zilf, but they're mostly about unused variables.)

**Comment by AlexProudfoot** [comment]
Oops, let’s handle this as a hotfix.

**Comment by AlexProudfoot** [comment]
Try that please.

**Comment by eriktorbjorn** [comment]
The "hotfix" branch builds without any unexpected problems.
